version: '3'

services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
      - recommendation-service
    networks:
      - microservice-network
    restart: always

  recommendation-service:
    build: ./microservice
    container_name: recommendation-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
    networks:
      - microservice-network
    restart: always

networks:
  microservice-network:
    driver: bridge

volumes:
  mysql-data: 